### ISSUE TITLE
TODO before announcement

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#134]
- [x] fix create token flow
- [x] fetch all tokens serverside on landing page
- [x] fetch real token values from server on details page
- [x] Form: remove form validation in realtime, only validate once the user submits
- [x] Form: make description optional
- [x] Form: show uploaded image once uploaded

- [x] BUY transaction (disable?)
- [x] SELL transaction (disable?)
- [x] add loading toaster UI during create token TX
